import type { RES_CambiosLog } from "../../../service/responses/_generic/cambios-log";
import type { EstadoBase } from "../../../shared/enums/_generic/estado-base";
import type { IDocumentoProgramacion } from "../../../shared/interfaces/documentos-programacion";
import type { DistribucionDetalleItem } from "../../programacion-despachos/service/programacion-despachos.responses";

export interface RES_LoteMineral {
  id: number;
  id_recepcion_unidad: number;
  id_empresa?: number | null;
  empresa_nombre?: string;
  id_proveedor_minero: number | null;
  proveedor_nombre?: string;
  proveedor_telefono?: string;
  id_proveedor_minero_recepcion: number | null;
  proveedor_nombre_recepcion?: string;
  id_empleado_registro: number;
  empleado_registro_nombre?: string;
  id_zona_origen: number | null;
  zona_origen_nombre?: string;
  correlativo: string;
  numero_correlativo: number | null;
  con_codigo_manual: boolean;
  numero_contacto: string | null;
  tipo_producto: string | null;
  tipo_mineral: string | null;
  condicion_ingreso: string | null;
  estado?: EstadoBase | string;
  log_cambios?: RES_CambiosLog[] | null;
  evidencias: Array<{
    url: string;
    path_relativo: string;
    nombre_original: string;
    extension: string;
  }> | null;
  peso_inicial: number | null;
  fecha_hora_peso_inicial: string | null;
  observacion_peso_inicial: string | null;
  peso_final: number | null;
  fecha_hora_peso_final: string | null;
  observacion_peso_final: string | null;
  peso_neto: number | null;
  peso_actual: number | null;
  id_vehiculo: number | null;
  vehiculo_placa: string | null;
  id_empresa_transporte: number | null;
  empresa_transporte_razon_social: string | null;
  id_tipo_vehiculo: number | null;
  tipo_vehiculo_nombre: string | null;
  id_conductor: number | null;
  conductor_nombre_completo: string | null;
  conductor_dni: string | null;
  created_at: string;
}

export interface RecepcionMineralResponse {
  id: number;
  id_empleado_registro: number;
  empleado_registro_nombre: string;
  id_vehiculo: number | null;
  vehiculo_placa: string | null;
  id_vehiculo_carreta: number | null;
  vehiculo_carreta_placa: string | null;
  id_empresa_transporte: number | null;
  empresa_transporte_razon_social: string | null;
  id_tipo_vehiculo: number | null;
  tipo_vehiculo_nombre: string | null;
  id_conductor: number | null;
  conductor_nombre_completo: string | null;
  conductor_dni: string | null;
  tipo_ingreso: string;
  fecha_hora_ingreso: string;
  fecha_hora_salida: string | null;
  fecha_hora_inicio_pesaje: string | null;
  fecha_hora_final_pesaje: string | null;
  evidencias: Array<{
    url: string;
    path_relativo: string;
    nombre_original: string;
    extension: string;
  }> | null;
  observacion: string | null;
  estado: string;
  estado_salida: string | null;
  estado_pesaje: string | null;
  es_programacion: number;
  id_sucursal: number | null;
  lotes: RES_LoteMineral[];
  distribucion_detalles: DistribucionDetalleItem[];
  documentos_programacion: IDocumentoProgramacion | null;
  log_cambios?: RES_CambiosLog[] | null;
}
